src/Entity/Participants.php
<?php

namespace App\Entity;

use App\Repository\ParticipantsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ParticipantsRepository::class)
 */
class Participants extends User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\OneToOne(targetEntity=Contacts::class, inversedBy="participants", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $contact;

    /**
     * @ORM\ManyToMany(targetEntity=Devis::class, mappedBy="participants")
     */
    private $devis;

    /**
     * @ORM\ManyToMany(targetEntity=Conventions::class, mappedBy="participants", cascade={"persist", "remove"})
     */
    private $conventions;

    
    public function __construct()
    {
        $this->devis = new ArrayCollection();
        $this->conventions = new ArrayCollection();
        
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function MakeIdentifiant($contact = null){
        //dd($this->getContact()->getPrenom());
        //crée un identifant 1ere lettre prénom + nom
        $identifiant = substr($this->getContact()->getPrenom(),0,1) . $this->getContact()->getNom();
        return $identifiant;

    }

    /**
     * @return Collection|Devis[]
     */
    public function getDevis(): Collection
    {
        return $this->devis;
    }


    // public function addDevi(Devis $devi): self
    // {
    //     if (!$this->devis->contains($devi)) {
    //         $this->devis[] = $devi;
    //         $devi->addParticipant($this);
    //     }

    //     return $this;
    // }

    // public function removeDevi(Devis $devi): self
    // {
    //     if ($this->devis->removeElement($devi)) {
    //         $devi->removeParticipant($this);
    //     }

    //     return $this;
    // }

    /**
     * @return Collection|Conventions[]
     */
    public function getConventions(): Collection
    {
        return $this->conventions;
    }

    public function addConvention(Conventions $convention): self
    {
        if (!$this->conventions->contains($convention)) {
            $this->conventions[] = $convention;
            $convention->addParticipant($this);
        }

        return $this;
    }

    public function removeConvention(Conventions $convention): self
    {
        if ($this->conventions->removeElement($convention)) {
            $convention->removeParticipant($this);
        }

        return $this;
    }

    public function getContact(): ?Contacts
    {
        return $this->contact;
    }

    public function setContact(Contacts $contact): self
    {
        $this->contact = $contact;

        return $this;
    }
    
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Validator\Constraints as SecurityAssert;


// tde 16-08-21 : pour avoir plusieurs type d'utilisateurs (formateurs/participants...)
// source : https://gkueny.fr/symfony-pouvoir-se-loguer-avec-deux-entites-differentes
// je place la class visée en extends de user
// je mets user en class abstraite "abstract"
// j'ajoute dans la route le joined pour les relier, 
// le DiscriminatorColumn qui va permettre de gérer les différents profils
// le DiscriminatorMap pour définir les profils en question

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"employes"="Employes","formateurs"="Formateurs", "participants"="Participants", "prospects"="Prospects"})
 */
abstract class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=80, unique=true)
     */
    private $identifiant;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=true)
     */
    protected $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fullname;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $reset_token;

    /**
     * @ORM\OneToOne(targetEntity=Commentaire::class, inversedBy="user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $commentaire;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdentifiant(): ?string
    {
        return $this->identifiant;
    }

    public function setIdentifiant(?string $identifiant): self
    {
        $this->identifiant = $identifiant;

        return $this;
    }

    abstract function MakeIdentifiant();

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->identifiant;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->identifiant;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    //tde 18-08-21 generation auto de mdp
    public function makePassword(){
        //mdp aléatoire: 
        $min = "abcdefghijklmnopqrstuvwxyz" ;
        $maj = "ABCDEFGHIJKLMOPQRSTUVWXYZ";
        $chiffre = "0123456789";
        $spe = "&@%!*";

        //stocke les choix possibles de caractères pour les prendre aléatoirement
        $choix = [$min,$min,$min,$maj,$maj,$maj,$chiffre,$chiffre,$spe,$spe];

        //stockage résultat
        $mdp ='';
        //boucle prends un caractère au hasard dans chaque liste de choix
        foreach ($choix as $val) {
            $mdp .= substr($val, rand( 0,  mb_strlen($val) -1), 1);
        }
        //renvoie le résultat mélangé
        return str_shuffle($mdp);
    }  

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(?string $fullname): self
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    public function getCommentaire(): ?Commentaire
    {
        return $this->commentaire;
    }

    public function setCommentaire(?Commentaire $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }


}

src/Form/ParticipantsType.php
<?php

namespace App\Form;


use App\Entity\Participants;
use App\Form\ParticipantContactType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class ParticipantsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ->add('field_name')
            ->add('contact', ParticipantContactType::class,[
                'label'=>false,
                
                
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Participants::class,
        ]);
    }
}

src/Controller/ParticipantsController.php
<?php

namespace App\Controller;

use App\Entity\Participants;
use App\Form\ParticipantsType;
use App\Repository\ParticipantsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;


/**
 * @Route("/participants")
 */
class ParticipantsController extends AbstractController
{
    /**
     * @Route("/", name="participants_index", methods={"GET"})
     */
    public function index(ParticipantsRepository $participantsRepository): Response
    {
        return $this->render('participants/index.html.twig', [
            'participants' => $participantsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="participants_new", methods={"GET","POST"})
     */
    public function new(Request $request,UserPasswordHasherInterface $hasher, MailerInterface $mailer, ParticipantsRepository $repo): Response
    {
        $participant = new Participants();
        $form = $this->createForm(ParticipantsType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            // tde 10/09/21 vérifie si l'identifiant existe déjà
            if($repo->findOneBy(["identifiant"=>$participant->getIdentifiant()])){
                //recup l'id le plus grand en bdd et ajoute 1
                $number = $repo->findBy([], ['id' => 'desc'],1,0);
                $number = intval($number[0]->getId()) + 1 ;
                //il l'ajoute à l'identifiant généré
                $participant->setIdentifiant($participant->MakeIdentifiant() . $number);
            }else{
                $participant->setIdentifiant($participant->MakeIdentifiant());
            }
dd($participant);

            //tde 17/08/21 encodage mdp avec hasher ⚠encoder est déprécié
            $mdp = $participant->makePassword();
            $participant->setPassword($hasher->hashPassword($participant, $mdp));
            
            $participant->setRoles(['ROLE_PARTICIPANT']);

            $entityManager->persist($participant);
            $entityManager->flush();

            //récuperer l'email qui est saisie dans le formulaire 
            $user = $form->getData()->getEmail();
            
            //envoie de mdp généré par l'email
            $message = (new Email())
            ->From('info@graphikchannel.com')
            ->To($user)
            ->text('Bonjour voici votre mot de passe  : '.$mdp);
            

            //envoie de mail
            $mailer->send($message);


            // j'intercepte la redirection pour vérifier ll'envoie de mail mais cette ligne sera décommenter plustard
            // return $this->redirectToRoute('participants_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('participants/new.html.twig', [
            'participant' => $participant,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="participants_show", methods={"GET"})
     */
    public function show(Participants $participant): Response
    {
        return $this->render('participants/show.html.twig', [
            'participant' => $participant,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="participants_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Participants $participant, ParticipantsRepository $repo , UserPasswordHasherInterface $hasher): Response
    {
        $form = $this->createForm(ParticipantsType::class, $participant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($repo->findOneBy(["identifiant" => $participant->getIdentifiant()])) {
                //recup l'id le plus grand en bdd et ajoute 1
                $number = $repo->findBy([], ['id' => 'desc'], 1, 0);
                $number = intval($number[0]->getId()) + 1;
                //il l'ajoute à l'identifiant généré
                $participant->setIdentifiant($participant->MakeIdentifiant() . $number);
            } else {
                $participant->setIdentifiant($participant->MakeIdentifiant());
            }
            $participant->setPassword($hasher->hashPassword($participant, $participant->getPassword()));
            $participant->setRoles(['ROLE_PARTICIPANT']);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('participants_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('participants/edit.html.twig', [
            'participant' => $participant,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="participants_delete", methods={"POST"})
     */
    public function delete(Request $request, Participants $participant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$participant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($participant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('participants_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/participants/_delete_form.html.twig
<form method="post" action="{{ path('participants_delete', {'id': participant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ participant.id) }}">
    <button class="btn"><i class="far fa-trash-alt text-danger"></i></button>
</form>

templates/participants/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/participants/edit.html.twig
{% extends 'base-admin.html.twig' %}


{% block title %}Modifier Participants{% endblock %}

{% block body %}
    <h1>Modifier Participants</h1>

    {{ include('participants/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('participants_index') }}">Retour</a>

    {{ include('participants/_delete_form.html.twig') }}
{% endblock %}

templates/participants/index.html.twig
{% extends 'base-admin.html.twig' %}


{% block title %}Participants{% endblock %}

{% block body %}
    <h1>Participants</h1>

    <table class="table" data-sorting="true" data-filtering="true" data-paging="true" data-paging-size="3">
        <thead>
            <tr>
                <th>Id</th>
                <th>Identifiant</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Image</th>
                <th>Fullname</th>
                <th>Reset_token</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for participant in participants %}
            <tr>
                <td>{{ participant.id }}</td>
                <td>{{ participant.identifiant }}</td>
                <td>{{ participant.email }}</td>
                <td>{{ participant.roles ? participant.roles|json_encode : '' }}</td>
                <td>{{ participant.password }}</td>
                <td>{{ participant.image }}</td>
                <td>{{ participant.fullname }}</td>
                <td>{{ participant.resetToken }}</td>
                <td>{{ participant.nom }}</td>
                <td>{{ participant.prenom }}</td>
                <td>
                    <a href="{{ path('participants_show', {'id': participant.id}) }}">voir</a>
                    <a href="{{ path('participants_edit', {'id': participant.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">Aucun résultat</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('participants_new') }}">Nouveau</a>
{% endblock %}

templates/participants/new.html.twig
{% extends 'base-admin.html.twig' %}


{% block title %}Nouveau Participants{% endblock %}

{% block body %}
    <h1>Ajouter un Participants</h1>

    {{ include('participants/_form.html.twig') }}

    <a href="{{ path('participants_index') }}">Retour</a>
{% endblock %}

templates/participants/show.html.twig
{% extends 'base-admin.html.twig' %}


{% block title %}Participants{% endblock %}

{% block body %}
    <h1>Participants</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ participant.id }}</td>
            </tr>
            <tr>
                <th>Identifiant</th>
                <td>{{ participant.identifiant }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ participant.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ participant.roles ? participant.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ participant.password }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ participant.image }}</td>
            </tr>
            <tr>
                <th>Fullname</th>
                <td>{{ participant.fullname }}</td>
            </tr>
            <tr>
                <th>Reset_token</th>
                <td>{{ participant.resetToken }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ participant.nom }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ participant.prenom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('participants_index') }}">Retour</a>

    <a href="{{ path('participants_edit', {'id': participant.id}) }}">Modifier</a>

    {{ include('participants/_delete_form.html.twig') }}
{% endblock %}